### ISSUE TITLE
Give me this error when import to pi hole

### ISSUE THREAD

**Issue by fivestar9105** [SM443/Pi-hole-Torrent-Blocklist#6]
[i] Target: https://github.com/SM443/Pi-hole-Torrent-Blocklist/blob/main/all-torrent-trackres.txt
  [   ] Status: Retrieval successful
tr: write error: Broken pipe
  [i] Imported 0 domains, ignoring 318 non-domain entries
      Sample of non-domain entries:
        - "
        - ">
        - 0;">
        - 175px">
        - 1rem;">

**Comment by iovcho** [comment]
Hi @fivestar9105  I am not pihole expert, but your url is wrong. Can you try with this
https://raw.githubusercontent.com/SM443/Pi-hole-Torrent-Blocklist/main/all-torrent-trackres.txt

You try to download html version, but must be in RAW format  -> 
https://raw.githubusercontent.com/SM443/Pi-hole-Torrent-Blocklist/main/all-torrent-trackres.txt

Best regards,
