### ISSUE TITLE
block this torrent sites

### ISSUE THREAD

**Issue by iovcho** [SM443/Pi-hole-Torrent-Blocklist#7]
Torrent trackers:

zelka.org
zamunda.se

**Comment by iovcho** [comment]
zamunda.ch

**Comment by SM443** [comment]
Added. Thank you. 

[f3cf7c9](https://github.com/SM443/Pi-hole-Torrent-Blocklist/commit/f3cf7c9b33523811f9527de5cfe4f83cdc2c26f7)
