### ISSUE TITLE
Pls add this to list

### ISSUE THREAD

**Issue by Thoudal** [SM443/Pi-hole-Torrent-Blocklist#8]
Hello and thank you for a great list.
I'm hoping to use your list since I don't like my kids to use torrent sites for downloading.
However the site thepiratebay.org is not blocked in your list (I see several like 1-thepiratebay.org etc) but not the actual main site.
/regards, Thoudal

**Comment by SM443** [comment]
Added. Thank you. 

[f3cf7c9](https://github.com/SM443/Pi-hole-Torrent-Blocklist/commit/f3cf7c9b33523811f9527de5cfe4f83cdc2c26f7)
